"""add ranking_rules to competition, add yellow_cards red_cards clean_sheets to ranking

Revision ID: 66517d3e359c
Revises: a7416ed7973f
Create Date: 2026-05-07 07:37:32.700299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66517d3e359c'
down_revision = 'a7416ed7973f'
branch_labels = None
depends_on = None


_DEFAULT_RANKING_RULES = '{"preset": "ligue_1", "tiebreaker_order": ["points", "head_to_head", "goal_difference", "goals_for", "fair_play"]}'


def upgrade():
    # ranking_rules: nullable=True d'abord pour backfill sur lignes existantes
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking_rules', sa.JSON(), nullable=True))

    op.execute(f"UPDATE competitions SET ranking_rules = '{_DEFAULT_RANKING_RULES}'::json WHERE ranking_rules IS NULL")

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.alter_column('ranking_rules', nullable=False)

    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yellow_cards', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('red_cards', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('clean_sheets', sa.Integer(), nullable=False, server_default='0'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rankings', schema=None) as batch_op:
        batch_op.drop_column('clean_sheets')
        batch_op.drop_column('red_cards')
        batch_op.drop_column('yellow_cards')

    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('ranking_rules')

    # ### end Alembic commands ###
